### ISSUE TITLE
Fails to build with GHC>=9.0, singletons >=3.0

### ISSUE THREAD

**Issue by vmchale** [expipiplus1/clash-wavedrom#1]
I tried to patch it myself [here](https://github.com/expipiplus1/clash-wavedrom/compare/master...vmchale:master) but I got stuck!

```
vanessa@vanessa-desktop /development/haskell/forks/clash-wavedrom 🌸 cabal build -w ghc-9.0.2 --constraint='clash-prelude>=1.6'
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - clash-wavedrom-0.0.0.0 (lib) (first run)
Preprocessing library for clash-wavedrom-0.0.0.0..
Building library for clash-wavedrom-0.0.0.0..
[1 of 3] Compiling Clash.WaveDrom.Internal ( src/Clash/WaveDrom/Internal.hs, /development/haskell/forks/clash-wavedrom/dist-newstyle/build/x86_64-linux/ghc-9.0.2/clash-wavedrom-0.0.0.0/build/Clash/WaveDrom/Internal.o, /development/haskell/forks/clash-wavedrom/dist-newstyle/build/x86_64-linux/ghc-9.0.2/clash-wavedrom-0.0.0.0/build/Clash/WaveDrom/Internal.dyn_o )

src/Clash/WaveDrom/Internal.hs:326:2: error:
    • Couldn't match type: SProxy p0
                           -> SSymbol n0 -> STree (WaveShape a0 n0)
                     with: SLambda f0
      Expected: SLambda f0
        Actual: Sing p0 -> Sing n0 -> Sing (WaveShape a0 n0)
    • Probable cause: ‘sWaveShapeP’ is applied to too few arguments
      In the first argument of ‘applySing’, namely ‘sWaveShapeP’
      In the first argument of ‘applySing’, namely
        ‘((applySing sWaveShapeP) sA)’
      In the second argument of ‘applySing’, namely
        ‘((applySing ((applySing sWaveShapeP) sA))
            ((applySing ((singFun1 @Show_Sym0) sShow_))
               ((applySing ((applySing ((singFun2 @(-@#@$)) (%-))) sI))
                  (sFromInteger (sing :: Sing 1)))))’
    • Relevant bindings include
        sA :: Sing t (bound at src/Clash/WaveDrom/Internal.hs:326:2)
        sIndexedDsc :: Sing t
                       -> Sing t1 -> Sing (Apply (Apply IndexedDscSym0 t) t1)
          (bound at src/Clash/WaveDrom/Internal.hs:326:2)
    |
326 | $(singletonsOnly [d|
    |  ^^^^^^^^^^^^^^^^^^^...
```

(not sure what is going on with singletons here)
